### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghtg** [IgaoGuru/Sequoia#4]
py .\detect.py
torch version: 1.11.0+cu113
Torch CUDA version: 11.3
torchvision version: 0.12.0+cu113
opencv version: 4.5.4-dev

Light_inference running on: NVIDIA GeForce GTX 1060 3GB
False False
detecting on: NVIDIA GeForce GTX 1060 3GB
Traceback (most recent call last):
  File "C:\Users\SASEN1\Desktop\Sequoia-main\detect.py", line 56, in <module>
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "C:\Users\SASEN1\Desktop\Sequoia-main\models\experimental.py", line 136, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
  File "C:\Users\SASEN1\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\SASEN1\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by raytsou** [comment]
https://stackoverflow.com/questions/54893134/not-able-to-load-a-pickle-file-cloning-from-others-repo-due-to-unpicklingerror
